//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kliens.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        int Sub(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiple", ReplyAction="*")]
        int Multiple(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiple", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultipleAsync(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divi", ReplyAction="*")]
        float Divi(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divi", ReplyAction="*")]
        System.Threading.Tasks.Task<float> DiviAsync(int A, int B);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Kliens.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Kliens.ServiceReference1.WebService1Soap>, Kliens.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int A, int B) {
            return base.Channel.Add(A, B);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int A, int B) {
            return base.Channel.AddAsync(A, B);
        }
        
        public int Sub(int A, int B) {
            return base.Channel.Sub(A, B);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int A, int B) {
            return base.Channel.SubAsync(A, B);
        }
        
        public int Multiple(int A, int B) {
            return base.Channel.Multiple(A, B);
        }
        
        public System.Threading.Tasks.Task<int> MultipleAsync(int A, int B) {
            return base.Channel.MultipleAsync(A, B);
        }
        
        public float Divi(int A, int B) {
            return base.Channel.Divi(A, B);
        }
        
        public System.Threading.Tasks.Task<float> DiviAsync(int A, int B) {
            return base.Channel.DiviAsync(A, B);
        }
    }
}
